---
title: "Lab Quiz 6"
author: "Katherine McAuley"
date: "November 1, 2016"
output: word_document
---
#Question 1
The comparison of correlations between two non-overlapping correlations, variables A1 & C1 and variables E1 & O1, was *$\Delta$r*=-.0099, 95% CI [-.1102, .0904], *p*=.84, *N* = 777. The CI is quite long. 

#Question 2
The comparison of two overlapping correlations, including variables A1 & C1 with variables A1 & E1, was *$\Delta$r*=-.0778, 95% CI[-.1840,.0239], *p*=.13, *N* = 777. The CI is quite long.

#Question 3
When comparing the correlation of variables A1 & E1 for both men(n=251) and women(n=518), *$\Delta$r*=.0171, 95% CI[-.1339,.1674], *p*=.82, *N*=777.

#Question 4
The comparison of two overlapping correlations, rating-raises and rating-critical, was *$\Delta$r*=.43, 95% CI [.0666, .7869], *p*=.02, *N* = 777. The confidence interval here is quite long and therefore the difference of these correlations could be between very weak and moderately strong. The only thing we can do is rule out a negative relationship. 

#Question 5
The comparison of correlations between two non-overlapping correlations, rating-raises and complaints-critical, was *$\Delta$r*=.4, 95% CI [.0149, .7768], *p*=.84, *N* = 777. The confidence interval here is quite long and therefore the difference of these correlations could be between very weak and moderately strong. The only thing we can do is rule out a negative relationship. 

#Question 6
When comparing the correlation of rating-raises for Study 1(n=30) and Study 2(n=3000), *$\Delta$r*=.56, 95% CI[.2596,.7570], *p*=.001, *N*=777. The confidence interval here is of moderate length, which allows us to say that the relationship between these correlations is between moderate-strong. 